### ISSUE TITLE
Error when extracting nests for bird-bird-bird

### ISSUE THREAD

**Issue by ethanwhite** [weecology/EvergladesWadingBird#51]
```python
/orange/ewhite/everglades/EvergladesWadingBird/Zooniverse/nest_detection.py:115: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  result_shp.to_file(filename)
/orange/ewhite/everglades/nest_crops//5217_6thBridge/5217_6thBridge_02_21_2020_projected.png raises tile cannot extend outside image
Traceback (most recent call last):
  File "/orange/ewhite/everglades/EvergladesWadingBird/Zooniverse/nest_detection.py", line 239, in <module>
    extract_nests(nest_shp, rgb_pool=rgb_pool, savedir="/orange/ewhite/everglades/nest_crops/", upload=False)
  File "/orange/ewhite/everglades/EvergladesWadingBird/Zooniverse/nest_detection.py", line 218, in extract_nests
    cv2.imwrite(filename, crop)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-2uwlt2pi/opencv/modules/imgcodecs/src/loadsave.cpp:803: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'
```

**Comment by bw4sz** [comment]
that's corrupted image warning, same as the JOULE raster's, some mismatch with the spatial projection, we'll need go back to andrew and the source image. The code in this repo just keeps whatever spatial information. Just that one raster?

**Comment by ethanwhite** [comment]
Ah, that makes sense. Let me check.

**Comment by ethanwhite** [comment]
ctually there's no file by that name in that location. There is no `5217_6thBridge_02_21_2020_projected.png` in `/orange/ewhite/everglades/nest_crops`. Does that mean that this error is upstream of the creation of that file?

**Comment by ethanwhite** [comment]
OK, I understand now, will go look in the upstream file.
